const ERROR_CODES = Object.freeze({
  VALIDATION_ERROR: "VALIDATION_ERROR",

  UNAUTHENTICATED: "UNAUTHENTICATED",
  FORBIDDEN: "FORBIDDEN",

  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ACCOUNT_INACTIVE: "ACCOUNT_INACTIVE",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",

  USER_NOT_FOUND: "USER_NOT_FOUND",

  ANALYSIS_NOT_FOUND: "ANALYSIS_NOT_FOUND",

  INVALID_ANALYSIS_ID: "INVALID_ANALYSIS_ID",

  INVALID_URL: "INVALID_URL",

  NOT_FOUND: "NOT_FOUND",

  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",

  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR"
});

module.exports = ERROR_CODES;